# Busca el .env tanto si ejecutas el proyecto completo como si ejecutas solo los tests de Maven
spring.config.import=optional:file:core/.env[.properties],optional:file:.env[.properties]

# ===================================================================
# Configuración de la Base de Datos (PostgreSQL en Docker)
# ===================================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# Configuración de JPA / Hibernate
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# Configuración de Redis
# ===================================================================
spring.data.redis.host=localhost
spring.data.redis.port=${REDIS_PORT}